/*
 Author:     Jiamin, hejiamin1995@gmail.com
 Date:       Nov 15, 2017
 Problem:    find the difference
 Difficulty: easy
 Notes:
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

//9ms
class Solution {
    public char findTheDifference(String s, String t) {
        
        int sumS = 0;
        int sumT = 0;
        int i = 0;
        for (i = 0; i < s.length(); i++) {
            sumS += s.charAt(i);
            sumT += t.charAt(i);
        }
        sumT += t.charAt(i);
        return (char)(sumT-sumS);
    }
}
